//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlacierLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlacierLauncher.Properties.Resources_zh-CN", typeof(Resources_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Java 路径: 的本地化字符串。
        /// </summary>
        internal static string JavaPathLabelText {
            get {
                return ResourceManager.GetString("JavaPathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器信息 的本地化字符串。
        /// </summary>
        internal static string LauncherInfoTagText {
            get {
                return ResourceManager.GetString("LauncherInfoTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Glacer 我的世界服务器启动器 的本地化字符串。
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java 未安装。请先访问https://www.oracle.com/cn/下载Java。 的本地化字符串。
        /// </summary>
        internal static string Mbox_JavaNotInstalledText {
            get {
                return ResourceManager.GetString("Mbox_JavaNotInstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器信息 的本地化字符串。
        /// </summary>
        internal static string ServerInfoTabText {
            get {
                return ResourceManager.GetString("ServerInfoTabText", resourceCulture);
            }
        }
    }
}
